/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.Dao_Cadastro;
import Model.Cadastro;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Bruna Leonel
 */
public class ManutençãoFuncionario extends javax.swing.JInternalFrame {
    Cadastro cad;
    Dao_Cadastro Dao_cad;
    
    /**
     * Creates new form CadastroFuncionario
     */
    public ManutençãoFuncionario() {
        
        cad = new Cadastro();
        Dao_cad = new Dao_Cadastro();
        initComponents();
        
        centralizarComponente();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        TxIdFunc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxNomeFunc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxEndereçoFunc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ComboVia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TxCidadeFunc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ComboEstado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        TxComplementoFunc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxBairroFunc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxTelefoneFunc = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        TxCelularFunc = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        TxEmailFunc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxFunção = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxUsuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxSenha = new javax.swing.JPasswordField();
        BtSalvarFunc = new javax.swing.JButton();
        BtIncluirFunc = new javax.swing.JButton();
        BtPesquisarFunc = new javax.swing.JButton();
        BtLimpar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtSair = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Manutenção");

        jLabel1.setText("Identificador");

        TxIdFunc.setEditable(false);
        TxIdFunc.setText("NOVO");

        jLabel2.setText("Nome");

        TxNomeFunc.setEditable(false);

        jLabel3.setText("Endereço");

        TxEndereçoFunc.setEditable(false);
        TxEndereçoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxEndereçoFuncActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de Via");

        ComboVia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Avenida", "Rua", "Rural" }));
        ComboVia.setToolTipText("");
        ComboVia.setEnabled(false);
        ComboVia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboViaActionPerformed(evt);
            }
        });

        jLabel5.setText("Cidade");

        TxCidadeFunc.setEditable(false);

        jLabel6.setText("UF");

        ComboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        ComboEstado.setToolTipText("");
        ComboEstado.setEnabled(false);

        jLabel7.setText("Complemento");

        TxComplementoFunc.setEditable(false);

        jLabel8.setText("Bairro");

        TxBairroFunc.setEditable(false);
        TxBairroFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxBairroFuncActionPerformed(evt);
            }
        });

        jLabel9.setText("Telefone Fixo");

        TxTelefoneFunc.setEditable(false);
        try {
            TxTelefoneFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setText("Telefone Celular");

        TxCelularFunc.setEditable(false);
        try {
            TxCelularFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setText("Email");

        TxEmailFunc.setEditable(false);

        jLabel12.setText("Função");

        TxFunção.setEditable(false);

        jLabel13.setText("Usuário");

        TxUsuario.setEditable(false);

        jLabel14.setText("Senha");

        TxSenha.setEditable(false);

        BtSalvarFunc.setText("Salvar");
        BtSalvarFunc.setEnabled(false);
        BtSalvarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarFuncActionPerformed(evt);
            }
        });

        BtIncluirFunc.setText("Incluir");
        BtIncluirFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirFuncActionPerformed(evt);
            }
        });

        BtPesquisarFunc.setText("Pesquisar");
        BtPesquisarFunc.setEnabled(false);
        BtPesquisarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisarFuncActionPerformed(evt);
            }
        });

        BtLimpar.setText("Limpar");
        BtLimpar.setEnabled(false);
        BtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimparActionPerformed(evt);
            }
        });

        BtAlterar.setText("Alterar");
        BtAlterar.setEnabled(false);
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        BtSair.setText("Sair");
        BtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxNomeFunc)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxCidadeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(ComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(TxTelefoneFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxCelularFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TxIdFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtPesquisarFunc)
                                        .addGap(30, 30, 30)
                                        .addComponent(BtLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TxComplementoFunc)
                        .addGap(18, 18, 18)
                        .addComponent(TxBairroFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboVia, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxEndereçoFunc)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(159, 159, 159))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxFunção, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14)
                                    .addComponent(TxEmailFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                    .addComponent(TxSenha)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(BtIncluirFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(BtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(BtSalvarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(BtSair, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxIdFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtPesquisarFunc)
                    .addComponent(BtLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboVia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxEndereçoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxBairroFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxComplementoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxCidadeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxCelularFunc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxEmailFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxTelefoneFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxFunção, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtIncluirFunc)
                    .addComponent(BtSalvarFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtAlterar)
                    .addComponent(BtSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void centralizarComponente() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }
    
    private void TxEndereçoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxEndereçoFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxEndereçoFuncActionPerformed

    private void ComboViaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboViaActionPerformed
    
    }//GEN-LAST:event_ComboViaActionPerformed

    private void BtIncluirFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirFuncActionPerformed
        TxNomeFunc.setEditable(true);
        TxEndereçoFunc.setEditable(true);
        TxComplementoFunc.setEditable(true);
        TxBairroFunc.setEditable(true);
        TxTelefoneFunc.setEditable(true);
        TxCelularFunc.setEditable(true);
        TxEmailFunc.setEditable(true);
        TxFunção.setEditable(true);
        TxUsuario.setEditable(true);
        TxSenha.setEditable(true);  
        ComboEstado.setEnabled(true);
        ComboVia.setEnabled(true);
        TxCidadeFunc.setEditable(true);
        BtSalvarFunc.setEnabled(true);
    }//GEN-LAST:event_BtIncluirFuncActionPerformed

    private void TxBairroFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxBairroFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxBairroFuncActionPerformed

    private void BtSalvarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarFuncActionPerformed
        if(TxIdFunc.getText().length()==0 || TxNomeFunc.getText().length()==0 || TxEndereçoFunc.getText().length()==0 || TxBairroFunc.getText().length()==0 || TxCidadeFunc.getText().length()==0 || TxTelefoneFunc.getText().length()==0 || TxCelularFunc.getText().length()==0 || TxEmailFunc.getText().length()==0 || TxFunção.getText().length()==0 || TxUsuario.getText().length()==0 || TxSenha.getText().length()==0 ||ComboVia.getSelectedItem().equals("Selecione")|| ComboEstado.getSelectedItem().equals("Selecione"))   {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } 
        else{
            JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso!");
            int op=0;
            if(op==0){
            TxIdFunc.setText("");
            TxNomeFunc.setText("");
            TxEndereçoFunc.setText("");
            TxComplementoFunc.setText("");
            TxBairroFunc.setText("");
            TxCidadeFunc.setText("");
            TxTelefoneFunc.setText("");
            TxCelularFunc.setText("");
            TxEmailFunc.setText("");
            TxFunção.setText("");
            TxUsuario.setText("");
            TxSenha.setText("");
            BtAlterar.setEnabled(true);
            BtPesquisarFunc.setEnabled(true);

            TxNomeFunc.setEditable(false);
            TxEndereçoFunc.setEditable(false);
            TxComplementoFunc.setEditable(false);
            TxBairroFunc.setEditable(false);
            TxTelefoneFunc.setEditable(false);
            TxCelularFunc.setEditable(false);
            TxEmailFunc.setEditable(false);
            TxFunção.setEditable(false);
            TxUsuario.setEditable(false);
            TxSenha.setEditable(false);  
            ComboEstado.setEnabled(false);
            ComboVia.setEnabled(false);
            TxCidadeFunc.setEditable(false);
            BtSalvarFunc.setEnabled(false);
            BtAlterar.setEnabled(false);
            }}    }//GEN-LAST:event_BtSalvarFuncActionPerformed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
            if(TxIdFunc.getText().isEmpty())
           {
               JOptionPane.showMessageDialog(null, "Digite o id que será alterado");
           }
           
           else
           {
               cad = new Cadastro();
               cad.setId(Integer.parseInt(TxIdFunc.getText()));
               cad.setNome(TxNomeFunc.getText());
               cad.setEndereço(TxEndereçoFunc.getText());
               cad.setComplemento(TxComplementoFunc.getText());
               cad.setBairro(TxBairroFunc.getText());
               cad.setTelefone(Integer.parseInt(TxTelefoneFunc.getText()));
               cad.setCelular(Integer.parseInt(TxCelularFunc.getText()));
               cad.setEmail(TxEmailFunc.getText());
               cad.setFunção(TxFunção.getText());
               cad.setUsuario(TxUsuario.getText());
               cad.setSenha(TxSenha.getText());
               cad.setEstado((String) ComboEstado.getSelectedItem());
               cad.setTipodevia((String) ComboVia.getSelectedItem());
               JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");
           
           }    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtPesquisarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisarFuncActionPerformed
        BtLimpar.setEnabled(true);
    }//GEN-LAST:event_BtPesquisarFuncActionPerformed

    private void BtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtSairActionPerformed

    private void BtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimparActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Deseja realmente limpar?", "Confirmação",JOptionPane.YES_NO_OPTION);
        
        if(op==0){
            TxIdFunc.setText("");
            TxNomeFunc.setText("");
            TxEndereçoFunc.setText("");
            TxComplementoFunc.setText("");
            TxBairroFunc.setText("");
            TxCidadeFunc.setText("");
            TxTelefoneFunc.setText("");
            TxCelularFunc.setText("");
            TxEmailFunc.setText("");
            TxFunção.setText("");
            TxUsuario.setText("");
            TxSenha.setText("");
            ComboEstado.setSelectedItem("Selecione");
            ComboVia.setSelectedItem("Selecione");
    }//GEN-LAST:event_BtLimparActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtIncluirFunc;
    private javax.swing.JButton BtLimpar;
    private javax.swing.JButton BtPesquisarFunc;
    private javax.swing.JButton BtSair;
    private javax.swing.JButton BtSalvarFunc;
    private javax.swing.JComboBox<String> ComboEstado;
    private javax.swing.JComboBox<String> ComboVia;
    private javax.swing.JTextField TxBairroFunc;
    private javax.swing.JFormattedTextField TxCelularFunc;
    private javax.swing.JTextField TxCidadeFunc;
    private javax.swing.JTextField TxComplementoFunc;
    private javax.swing.JTextField TxEmailFunc;
    private javax.swing.JTextField TxEndereçoFunc;
    private javax.swing.JTextField TxFunção;
    private javax.swing.JTextField TxIdFunc;
    private javax.swing.JTextField TxNomeFunc;
    private javax.swing.JPasswordField TxSenha;
    private javax.swing.JFormattedTextField TxTelefoneFunc;
    private javax.swing.JTextField TxUsuario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    // End of variables declaration//GEN-END:variables
}
